### ISSUE TITLE
Missing proto files from grpc and proto modules

### ISSUE THREAD

**Issue by BenWhitehead** [googleapis/java-trace#9]
After being split out from google-cloud-java, the maven config to include proto files as resources in jars was lots.

I've opened a PR https://github.com/googleapis/java-shared-config/pull/21 to add the new shared config, once that is merged and released we can bump here and be fixed.

**Comment by chingor13** [comment]
Great spot, thanks!

**Comment by chingor13** [comment]
This should be fixed with the shared-config updates.
